export async function GET() {
  const booksData = [
    {
      id: 1,
      name: "Clean Code",
      author: "Robert C. Martin",
      publishDate: "2008-08-01",
      rating: 4.8,
    },
    {
      id: 2,
      name: "The Pragmatic Programmer",
      author: "Andrew Hunt",
      publishDate: "1999-10-30",
      rating: 4.7,
    },
    {
      id: 3,
      name: "JavaScript: The Good Parts",
      author: "Douglas Crockford",
      publishDate: "2008-05-15",
      rating: 4.5,
    },
    {
      id: 4,
      name: "You Don’t Know JS",
      author: "Kyle Simpson",
      publishDate: "2015-12-27",
      rating: 4.6,
    },
    {
      id: 5,
      name: "Eloquent JavaScript",
      author: "Marijn Haverbeke",
      publishDate: "2018-12-04",
      rating: 4.4,
    },
    {
      id: 6,
      name: "Design Patterns",
      author: "Erich Gamma",
      publishDate: "1994-10-21",
      rating: 4.7,
    },
    {
      id: 7,
      name: "Refactoring",
      author: "Martin Fowler",
      publishDate: "1999-07-08",
      rating: 4.6,
    },
    {
      id: 8,
      name: "Code Complete",
      author: "Steve McConnell",
      publishDate: "2004-06-09",
      rating: 4.8,
    },
    {
      id: 9,
      name: "Introduction to Algorithms",
      author: "Thomas H. Cormen",
      publishDate: "2009-07-31",
      rating: 4.9,
    },
    {
      id: 10,
      name: "Cracking the Coding Interview",
      author: "Gayle Laakmann McDowell",
      publishDate: "2015-07-01",
      rating: 4.7,
    },

    {
      id: 11,
      name: "Atomic Habits",
      author: "James Clear",
      publishDate: "2018-10-16",
      rating: 4.8,
    },
    {
      id: 12,
      name: "Deep Work",
      author: "Cal Newport",
      publishDate: "2016-01-05",
      rating: 4.6,
    },
    {
      id: 13,
      name: "The Lean Startup",
      author: "Eric Ries",
      publishDate: "2011-09-13",
      rating: 4.5,
    },
    {
      id: 14,
      name: "Zero to One",
      author: "Peter Thiel",
      publishDate: "2014-09-16",
      rating: 4.4,
    },
    {
      id: 15,
      name: "Hooked",
      author: "Nir Eyal",
      publishDate: "2014-11-04",
      rating: 4.3,
    },
    {
      id: 16,
      name: "Thinking, Fast and Slow",
      author: "Daniel Kahneman",
      publishDate: "2011-10-25",
      rating: 4.6,
    },
    {
      id: 17,
      name: "Rich Dad Poor Dad",
      author: "Robert Kiyosaki",
      publishDate: "1997-04-01",
      rating: 4.5,
    },
    {
      id: 18,
      name: "The Psychology of Money",
      author: "Morgan Housel",
      publishDate: "2020-09-08",
      rating: 4.8,
    },
    {
      id: 19,
      name: "Sapiens",
      author: "Yuval Noah Harari",
      publishDate: "2011-01-01",
      rating: 4.7,
    },
    {
      id: 20,
      name: "Homo Deus",
      author: "Yuval Noah Harari",
      publishDate: "2015-01-01",
      rating: 4.6,
    },

    {
      id: 21,
      name: "The Alchemist",
      author: "Paulo Coelho",
      publishDate: "1988-04-15",
      rating: 4.3,
    },
    {
      id: 22,
      name: "Ikigai",
      author: "Héctor García",
      publishDate: "2016-08-29",
      rating: 4.2,
    },
    {
      id: 23,
      name: "Start With Why",
      author: "Simon Sinek",
      publishDate: "2009-10-06",
      rating: 4.5,
    },
    {
      id: 24,
      name: "Grit",
      author: "Angela Duckworth",
      publishDate: "2016-05-03",
      rating: 4.4,
    },
    {
      id: 25,
      name: "Drive",
      author: "Daniel H. Pink",
      publishDate: "2009-12-29",
      rating: 4.3,
    },

    {
      id: 26,
      name: "The Subtle Art of Not Giving a F*ck",
      author: "Mark Manson",
      publishDate: "2016-09-13",
      rating: 4.1,
    },
    {
      id: 27,
      name: "Essentialism",
      author: "Greg McKeown",
      publishDate: "2014-04-15",
      rating: 4.4,
    },
    {
      id: 28,
      name: "Meditations",
      author: "Marcus Aurelius",
      publishDate: "180-01-01",
      rating: 4.7,
    },
    {
      id: 29,
      name: "The Art of War",
      author: "Sun Tzu",
      publishDate: "500-01-01",
      rating: 4.6,
    },
    {
      id: 30,
      name: "The 4-Hour Workweek",
      author: "Tim Ferriss",
      publishDate: "2007-04-24",
      rating: 4.3,
    },

    {
      id: 31,
      name: "Thinking in JavaScript",
      author: "Addy Osmani",
      publishDate: "2013-01-01",
      rating: 4.5,
    },
    {
      id: 32,
      name: "Node.js Design Patterns",
      author: "Mario Casciaro",
      publishDate: "2014-07-01",
      rating: 4.6,
    },
    {
      id: 33,
      name: "Learning React",
      author: "Alex Banks",
      publishDate: "2020-06-25",
      rating: 4.4,
    },
    {
      id: 34,
      name: "React Up & Running",
      author: "Stoyan Stefanov",
      publishDate: "2016-03-01",
      rating: 4.2,
    },
    {
      id: 35,
      name: "Next.js in Action",
      author: "Nader Dabit",
      publishDate: "2020-10-10",
      rating: 4.7,
    },

    {
      id: 36,
      name: "Python Crash Course",
      author: "Eric Matthes",
      publishDate: "2015-11-01",
      rating: 4.8,
    },
    {
      id: 37,
      name: "Automate the Boring Stuff",
      author: "Al Sweigart",
      publishDate: "2015-04-14",
      rating: 4.7,
    },
    {
      id: 38,
      name: "Fluent Python",
      author: "Luciano Ramalho",
      publishDate: "2015-08-20",
      rating: 4.6,
    },
    {
      id: 39,
      name: "Learning SQL",
      author: "Alan Beaulieu",
      publishDate: "2009-06-01",
      rating: 4.3,
    },
    {
      id: 40,
      name: "Head First Design Patterns",
      author: "Eric Freeman",
      publishDate: "2004-10-25",
      rating: 4.7,
    },

    {
      id: 41,
      name: "Data Structures in JavaScript",
      author: "Loiane Groner",
      publishDate: "2016-01-01",
      rating: 4.4,
    },
    {
      id: 42,
      name: "Algorithms Unlocked",
      author: "Thomas H. Cormen",
      publishDate: "2013-03-01",
      rating: 4.5,
    },
    {
      id: 43,
      name: "The Road to React",
      author: "Robin Wieruch",
      publishDate: "2017-01-01",
      rating: 4.6,
    },
    {
      id: 44,
      name: "Effective JavaScript",
      author: "David Herman",
      publishDate: "2012-12-27",
      rating: 4.5,
    },
    {
      id: 45,
      name: "Web Development with Node",
      author: "Various Authors",
      publishDate: "2021-05-01",
      rating: 4.3,
    },

    {
      id: 46,
      name: "Clean Architecture",
      author: "Robert C. Martin",
      publishDate: "2017-09-20",
      rating: 4.7,
    },
    {
      id: 47,
      name: "Domain-Driven Design",
      author: "Eric Evans",
      publishDate: "2003-08-30",
      rating: 4.6,
    },
    {
      id: 48,
      name: "Microservices Patterns",
      author: "Chris Richardson",
      publishDate: "2018-10-30",
      rating: 4.5,
    },
    {
      id: 49,
      name: "System Design Interview",
      author: "Alex Xu",
      publishDate: "2020-07-01",
      rating: 4.8,
    },
    {
      id: 50,
      name: "Grokking Algorithms",
      author: "Aditya Bhargava",
      publishDate: "2016-05-01",
      rating: 4.7,
    },
  ];

  return Response.json(booksData);
}
