export async function GET() {
  const studentsData = [
    {
      id: 1,
      username: "johnsmith",
      name: "John Smith",
      email: "john.smith@example.com",
      address: "123 Maple St, New York, NY",
      phone: "+1-555-1001",
    },
    {
      id: 2,
      username: "emilyjohnson",
      name: "Emily Johnson",
      email: "emily.johnson@example.com",
      address: "456 Oak Ave, Los Angeles, CA",
      phone: "+1-555-1002",
    },
    {
      id: 3,
      username: "michaelbrown",
      name: "Michael Brown",
      email: "michael.brown@example.com",
      address: "789 Pine Rd, Chicago, IL",
      phone: "+1-555-1003",
    },
    {
      id: 4,
      username: "sarahdavis",
      name: "Sarah Davis",
      email: "sarah.davis@example.com",
      address: "101 Cedar Ln, Houston, TX",
      phone: "+1-555-1004",
    },
    {
      id: 5,
      username: "davidwilson",
      name: "David Wilson",
      email: "david.wilson@example.com",
      address: "202 Birch Dr, Phoenix, AZ",
      phone: "+1-555-1005",
    },
    {
      id: 6,
      username: "jessicamiller",
      name: "Jessica Miller",
      email: "jessica.miller@example.com",
      address: "303 Elm St, Philadelphia, PA",
      phone: "+1-555-1006",
    },
    {
      id: 7,
      username: "danielmoore",
      name: "Daniel Moore",
      email: "daniel.moore@example.com",
      address: "404 Walnut Ave, San Antonio, TX",
      phone: "+1-555-1007",
    },
    {
      id: 8,
      username: "ashleytaylor",
      name: "Ashley Taylor",
      email: "ashley.taylor@example.com",
      address: "505 Spruce Rd, San Diego, CA",
      phone: "+1-555-1008",
    },
    {
      id: 9,
      username: "mattanderson",
      name: "Matthew Anderson",
      email: "matt.anderson@example.com",
      address: "606 Willow Dr, Dallas, TX",
      phone: "+1-555-1009",
    },
    {
      id: 10,
      username: "oliviathomas",
      name: "Olivia Thomas",
      email: "olivia.thomas@example.com",
      address: "707 Cherry Ln, San Jose, CA",
      phone: "+1-555-1010",
    },
    {
      id: 11,
      username: "jamesjackson",
      name: "James Jackson",
      email: "james.jackson@example.com",
      address: "808 Aspen St, Austin, TX",
      phone: "+1-555-1011",
    },
    {
      id: 12,
      username: "sophiamartin",
      name: "Sophia Martin",
      email: "sophia.martin@example.com",
      address: "909 Poplar Ave, Jacksonville, FL",
      phone: "+1-555-1012",
    },
    {
      id: 13,
      username: "benjaminlee",
      name: "Benjamin Lee",
      email: "benjamin.lee@example.com",
      address: "111 Cypress Rd, Fort Worth, TX",
      phone: "+1-555-1013",
    },
    {
      id: 14,
      username: "isabellaperez",
      name: "Isabella Perez",
      email: "isabella.perez@example.com",
      address: "222 Magnolia Dr, Columbus, OH",
      phone: "+1-555-1014",
    },
    {
      id: 15,
      username: "williamwhite",
      name: "William White",
      email: "william.white@example.com",
      address: "333 Redwood Ln, Charlotte, NC",
      phone: "+1-555-1015",
    },
    {
      id: 16,
      username: "miathompson",
      name: "Mia Thompson",
      email: "mia.thompson@example.com",
      address: "444 Palm St, Indianapolis, IN",
      phone: "+1-555-1016",
    },
    {
      id: 17,
      username: "ethanharris",
      name: "Ethan Harris",
      email: "ethan.harris@example.com",
      address: "555 Sequoia Ave, Seattle, WA",
      phone: "+1-555-1017",
    },
    {
      id: 18,
      username: "abigailclark",
      name: "Abigail Clark",
      email: "abigail.clark@example.com",
      address: "666 Dogwood Rd, Denver, CO",
      phone: "+1-555-1018",
    },
    {
      id: 19,
      username: "alexrodriguez",
      name: "Alexander Rodriguez",
      email: "alex.rodriguez@example.com",
      address: "777 Hickory Dr, Boston, MA",
      phone: "+1-555-1019",
    },
    {
      id: 20,
      username: "charlottelewis",
      name: "Charlotte Lewis",
      email: "charlotte.lewis@example.com",
      address: "888 Sycamore Ln, Nashville, TN",
      phone: "+1-555-1020",
    },
  ];

  return Response.json(studentsData);
}
